server:
  port: 7001


spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
     registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
     fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
     serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己(如果不配置则默认本机8761端口)
       #defaultZone: http://localhost:6001/eureka/
       defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

  instance:
      instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名 了
      preferIpAddress: true #访问路径可以显示IP地址
zuul:
  routes:
    provider-product: #路由名称，名称任意，路由名称唯一
      path: /product/** #访问路径
      serviceId: microservice-product #指定服务id，会自动从eureka中找到此服务的ip和端口
      stripPrefix: false
